Repository mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution, pull requests merged in 2022-10, with the labels that each got.

#95 Add Vahsify's "The Fury Within 1.02" gateway
  CHANGELOG.md
  SlashGaming-Diablo-II-Free-Resolution/resource/resource.rc
  SlashGaming-Diablo-II-Free-Resolution/src/helper/game_resolution.cc
Labels: enhancement

#97 Add precompiled headers
  CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/pch.h
  SlashGaming-Diablo-II-Free-Resolution/src/pch.hpp
Labels: enhancement

#91 Add 1.10 support
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client_draw_interface_bar_background_patch/d2client_draw_interface_bar_background_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client_draw_interface_bar_background_patch/d2client_draw_interface_bar_background_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client_draw_screen_background_patch/d2client_draw_screen_background_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client_draw_screen_background_patch/d2client_draw_screen_background_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client_enable_800_interface_bar_patch/d2client_enable_800_interface_bar_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client_enable_800_interface_bar_patch/d2client_enable_800_interface_bar_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client_enable_800_new_skill_button_patch/d2client_enable_800_new_skill_button_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client_enable_800_new_skill_button_patch/d2client_enable_800_new_skill_button_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client_enable_800_new_stats_button_patch/d2client_enable_800_new_stats_button_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client_enable_800_new_stats_button_patch/d2client_enable_800_new_stats_button_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/inventory/d2common_get_global_belt_record_patch/d2common_get_global_belt_record_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/inventory/d2common_get_global_belt_record_patch/d2common_get_global_belt_record_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/inventory/d2common_get_global_belt_slot_position_patch/d2common_get_global_belt_slot_position_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/inventory/d2common_get_global_belt_slot_position_patch/d2common_get_global_belt_slot_position_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/inventory/d2common_get_global_equipment_slot_layout_patch/d2common_get_global_equipment_slot_layout_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/inventory/d2common_get_global_equipment_slot_layout_patch/d2common_get_global_equipment_slot_layout_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/inventory/d2common_get_global_inventory_grid_layout_patch/d2common_get_global_inventory_grid_layout_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/inventory/d2common_get_global_inventory_grid_layout_patch/d2common_get_global_inventory_grid_layout_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/inventory/d2common_get_global_inventory_position_patch/d2common_get_global_inventory_position_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/inventory/d2common_get_global_inventory_position_patch/d2common_get_global_inventory_position_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_disable_mouse_click_on_screen_patch/d2client_disable_mouse_click_on_screen_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_disable_mouse_click_on_screen_patch/d2client_disable_mouse_click_on_screen_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_draw_resolution_text_patch/d2client_draw_resolution_text.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_draw_resolution_text_patch/d2client_draw_resolution_text_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_draw_resolution_text_patch/d2client_draw_resolution_text_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_get_resolution_registry_patch/d2client_get_resolution_registry_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_get_resolution_registry_patch/d2client_get_resolution_registry_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_general_display_width_and_height_patch/d2client_set_general_display_width_and_height_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_general_display_width_and_height_patch/d2client_set_general_display_width_and_height_patch_1_09.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_resolution_from_options_menu_patch/d2client_set_resolution_from_options_menu.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_resolution_from_options_menu_patch/d2client_set_resolution_from_options_menu_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_resolution_from_options_menu_patch/d2client_set_resolution_from_options_menu_patch_1_09.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_resolution_registry_patch/d2client_set_resolution_registry_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_resolution_registry_patch/d2client_set_resolution_registry_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_screen_shift_patch/d2client_set_screen_shift_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_screen_shift_patch/d2client_set_screen_shift_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_unload_cel_file_collection_patch/d2client_unload_cel_file_collection_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_unload_cel_file_collection_patch/d2client_unload_cel_file_collection_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2gfx_set_display_width_and_height_patch/d2gfx_set_display_width_and_height_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2gfx_set_display_width_and_height_patch/d2gfx_set_display_width_and_height_patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/sgd2mapi_extension/game_function/d2client_function/d2client_draw_screens.cpp
Labels: enhancement

#98 Add D2Client SetTileCullingBound patch
  CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_tile_culling_bound_patch/d2client_set_tile_culling_bound.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_tile_culling_bound_patch/d2client_set_tile_culling_bound.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_tile_culling_bound_patch/d2client_set_tile_culling_bound_patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_tile_culling_bound_patch/d2client_set_tile_culling_bound_patch.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_tile_culling_bound_patch/d2client_set_tile_culling_bound_patch_1_07.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_tile_culling_bound_patch/d2client_set_tile_culling_bound_patch_1_07.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_tile_culling_bound_patch/d2client_set_tile_culling_bound_patch_1_07_shim.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_tile_culling_bound_patch/d2client_set_tile_culling_bound_patch_1_07_shim.h
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_tile_culling_bound_patch/d2client_set_tile_culling_bound_patch_1_11.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_tile_culling_bound_patch/d2client_set_tile_culling_bound_patch_1_11.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_tile_culling_bound_patch/d2client_set_tile_culling_bound_patch_1_11_shim.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_tile_culling_bound_patch/d2client_set_tile_culling_bound_patch_1_11_shim.h
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/required_patches.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/required_patches.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/sgd2mapi_extension/game_variable/d2gfx/is_perspective_mode_enabled.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/sgd2mapi_extension/game_variable/d2gfx/is_perspective_mode_enabled.hpp
Labels: bug, enhancement

#99 Disable thread library calls
  SlashGaming-Diablo-II-Free-Resolution/src/dll_main.cc
Labels: enhancement

#100 Fix Glide window resize on 800x600 replacement
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2glide_set_display_width_and_height_patch/d2glide_set_display_width_and_height.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/glide3x_gr_sst_win_open_patch/glide3x_gr_sst_win_open.cc
Labels: bug

#101 Fix crash when 640x480 is the only resolution
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_resolution_registry_patch/d2client_set_resolution_registry.cc
Labels: bug

#102 Prepare for 3.0.3.0
  CHANGELOG.md
  README.md
  SlashGaming-Diablo-II-Free-Resolution/resource/resource.rc
Labels: bug, enhancement

#104 Update .gitignore
  .gitignore
Labels: enhancement

#106 Restructure draw patches folder
  CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/patches/CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/disable_scroll_of_inifuss_rect/CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/disable_scroll_of_inifuss_rect/patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/disable_scroll_of_inifuss_rect/patch.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/disable_scroll_of_inifuss_rect/patch_1_07.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/disable_scroll_of_inifuss_rect/patch_1_07.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/draw_d2client_dibb_patch_1_09d_shim.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/draw_d2client_dibb_patch_lod_1_14c_shim.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/draw_d2client_dibb_patch_lod_1_14d_shim.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/patch.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/patch_1_09d.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/patch_lod_1_14c.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/patch_lod_1_14c.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/patch_lod_1_14d.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/patch_lod_1_14d.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/replacement.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/replacement.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_screen_background/CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_screen_background/draw_d2client_dsb_patch_1_09d_shim.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_screen_background/patch.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_screen_background/patch.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_screen_background/patch_1_09d.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_screen_background/patch_1_09d.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_screen_background/replacement.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_screen_background/replacement.hpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/draw_patches.hpp
Labels: documentation

#107 Extend tile culling bound more
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_tile_culling_bound_patch/d2client_set_tile_culling_bound.cc
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_set_tile_culling_bound_patch/d2client_set_tile_culling_bound_patch.cc
Labels: bug

#110 Hide DisableThreadLibraryCalls in DllMain
  SlashGaming-Diablo-II-Free-Resolution/src/dll_main.cc
Labels: bug

#111 Add Diablo2Online gateway
  SlashGaming-Diablo-II-Free-Resolution/resource/resource.rc
  SlashGaming-Diablo-II-Free-Resolution/src/helper/game_resolution.cc
Labels: enhancement

#113 Fix up file names to be consistent
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/disable_scroll_of_inifuss_rect/CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/disable_scroll_of_inifuss_rect/patch.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/disable_scroll_of_inifuss_rect/patch_1_07.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/patch.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/patch_1_09d.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/patch_1_09d_shim_d2client_draw_interface_bar_background.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/patch_lod_1_14c_shim_d2client_draw_interface_bar_background.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/patch_lod_1_14d_shim_d2client_draw_interface_bar_background.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_interface_bar_background/replacement.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_screen_background/CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_screen_background/patch.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_screen_background/patch_1_09d.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_screen_background/patch_1_09d_shim_d2client_draw_screen_background.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/draw/d2client/draw_screen_background/replacement.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_interface_bar/CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_interface_bar/patch.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_interface_bar/patch_1_09d.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_interface_bar/patch_1_09d_shim_d2client_enable_800_interface_bar.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_interface_bar/patch_1_12a.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_interface_bar/patch_1_12a_shim_d2client_enable_800_interface_bar.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_interface_bar/patch_1_13c.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_interface_bar/patch_1_13c_shim_d2client_enable_800_interface_bar.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_interface_bar/replacement.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_skill_button/CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_skill_button/patch.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_skill_button/patch_1_09d.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_skill_button/patch_1_09d_shim_d2client_enable_800_new_skill_button.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_skill_button/patch_1_12a.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_skill_button/patch_1_12a_shim_d2client_enable_800_new_skill_button.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_skill_button/patch_1_13c.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_skill_button/patch_1_13c_shim_d2client_enable_800_new_skill_button.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_skill_button/replacement.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_stats_button/CMakeLists.txt
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_stats_button/patch.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_stats_button/patch_1_09d.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_stats_button/patch_1_09d_shim_d2client_enable_800_new_stats_button.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_stats_button/patch_1_12a.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_stats_button/patch_1_12a_shim_d2client_enable_800_new_stats_button.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_stats_button/patch_1_13c.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_stats_button/patch_1_13c_shim_d2client_enable_800_new_stats_button.asm
  SlashGaming-Diablo-II-Free-Resolution/src/patches/interface_bar/d2client/enable_800_new_stats_button/replacement.cpp
  SlashGaming-Diablo-II-Free-Resolution/src/patches/required/required_patches.hpp
Labels: documentation
